import {state,current,member,connected,family,visibleField,canSeePost} from './store.js';
import {esc,avatar,personLink,stamp,day,icon,audienceLabel,button as b,empty} from './ui.js';
import {challengeVisible,deadlinePassed} from './model.js';
export function mediaHTML(media,type,alt='',cls=''){if(!media)return '';const safe=/^(data:(image\/(jpeg|png|webp|gif)|video\/(mp4|webm));base64,|assets\/)/.test(media);if(!safe)return '';return type==='video'?'<video class="post-photo '+cls+'" src="'+esc(media)+'" controls preload="metadata" aria-label="'+esc(alt||'Attached video')+'"></video>':'<img class="post-photo '+cls+'" src="'+esc(media)+'" alt="'+esc(alt)+'" loading="lazy">';}
export function challengeCard(c){if(!c)return '';return '<a class="challenge-card" href="#challenge/'+c.id+'"><div class="challenge-art">'+c.prize+'<span>STARS</span></div><div><span class="eyebrow">'+(c.status==='awarded'?'CHALLENGE COMPLETED':deadlinePassed(c)?'SUBMISSIONS CLOSED':'A CHALLENGE FROM '+esc(member(c.creator)?.name.split(' ')[0]))+'</span><h3>'+esc(c.title)+'</h3><p>'+c.entries.length+' '+(c.entries.length===1?'entry':'entries')+' · '+(c.status==='open'?'Closes '+esc(c.deadline):esc(c.status))+'</p><span class="text-link">View challenge →</span></div></a>';}
export function renderPost(p){
 if(!canSeePost(p))return '';
 const comments=p.comments.filter(c=>connected(c.author,state.current));
 const votes=p.votes?Object.values(p.votes):[],voted=p.votes?.[state.current],like=p.likes.includes(state.current);
 return '<article class="post" data-post="'+p.id+'"><div class="post-head">'+avatar(p.author)+'<div>'+personLink(p.author)+(p.wall!==p.author?' <span class="muted">→</span> '+personLink(p.wall):'')+'<div class="metadata">'+stamp(p.created)+' · '+(p.audience==='family'?audienceLabel(p.audience):p.wall!==p.author?'Shared connections':'Connections')+(p.pending?' · Awaiting approval':'')+'</div></div>'+b('···','post-options','post-more','data-id="'+p.id+'" aria-label="Options for post by '+esc(member(p.author)?.name)+'"')+'</div><p class="post-text">'+esc(p.text)+'</p>'+
 (p.type==='photo'?mediaHTML(p.media,p.mediaType,p.alt)+(p.caption?'<div class="caption">'+esc(p.caption)+(p.creditUrl&&/^https:\/\/commons\.wikimedia\.org\//.test(p.creditUrl)?' · <a href="'+esc(p.creditUrl)+'" target="_blank" rel="noreferrer">Photo source</a>':'')+(p.licenseUrl&&/^https:\/\/creativecommons\.org\//.test(p.licenseUrl)?' · <a href="'+esc(p.licenseUrl)+'" target="_blank" rel="noreferrer">License</a>':'')+'</div>':''):
 p.type==='challenge'?challengeCard(state.challenges.find(c=>c.id===p.challenge)):
 p.type==='poll'?'<div class="poll">'+p.options.map((option,i)=>'<button data-action="vote" data-id="'+p.id+'" data-value="'+i+'" class="'+(voted===i?'voted':'')+'" style="--percent:'+(votes.length?Math.round(votes.filter(v=>v===i).length/votes.length*100):0)+'%" aria-pressed="'+(voted===i)+'"><span>'+esc(option)+'</span>'+(voted!==undefined?'<strong>'+Math.round(votes.filter(v=>v===i).length/votes.length*100)+'%</strong>':'')+'</button>').join('')+'<span class="metadata">'+votes.length+' votes · '+(voted!==undefined?'Your vote is saved. Choose again to change it.':'Choose one option.')+'</span></div>':'')+
 (p.pending?(p.wall===state.current?'<div class="approval-bar"><span>Held under the previous approval setting.</span>'+b('Publish','approve','primary small','data-id="'+p.id+'"')+b('Decline','decline','small','data-id="'+p.id+'"')+'</div>':'<div class="notice">Submitted to '+esc(member(p.wall)?.name)+' for approval. Audience: '+audienceLabel(p.audience)+'.</div>'):
 '<div class="post-actions">'+b(icon(like?'♥':'♡')+(like?'Liked':'Like')+' <span>'+p.likes.length+'</span>','like',like?'liked':'','data-id="'+p.id+'" aria-pressed="'+like+'"')+b(icon('messages')+'Reply <span>'+comments.length+'</span>','reply','','data-id="'+p.id+'"')+(p.author!==state.current?b(icon('star')+'Give Stars','gift','','data-id="'+p.id+'"'):'')+'<span class="metadata">'+(p.gifts?p.gifts+' Stars received':'')+'</span></div>')+
 (comments.length?'<div class="comments">'+comments.map(c=>'<div class="comment">'+avatar(c.author,'tiny')+'<div>'+personLink(c.author)+'<p>'+esc(c.text)+'</p></div></div>').join('')+'</div>':'')+'</article>';
}
export function composer(wall=state.current){return '<section class="composer" aria-label="Create a post"><div class="composer-input">'+avatar(state.current)+b(wall===state.current?'What’s happening in your world?':'Write something on '+esc(member(wall)?.name.split(' ')[0])+'’s wall…','compose','compose-prompt','data-wall="'+wall+'"')+'</div><div class="composer-footer"><div>'+b(icon('photo')+'Photo / video','compose','','data-value="photo" data-wall="'+wall+'"')+b(icon('poll')+'Poll','compose','','data-value="poll" data-wall="'+wall+'"')+(wall===state.current?b(icon('challenge')+'Challenge','compose','','data-value="challenge"'):'')+'</div>'+b('Write a post','compose','primary small','data-wall="'+wall+'"')+'</div></section>';}
export function postList(posts){return posts.map((p,i,a)=>(i===0||day(p.created)!==day(a[i-1].created)?'<div class="date-divider"><span>'+day(p.created)+'</span></div>':'')+renderPost(p)).join('');}
export function caughtUp(){return '<div class="caught-up"><span>✓</span><h3>You’re all caught up.</h3></div>';}
export function fieldValue(p,key){if(!visibleField(p.id,key))return '<span class="private-field">Private</span>';const v=p[key];if(Array.isArray(v))return v.length?v.map(t=>'<span class="tag">'+esc(t)+'</span>').join(''):'<span class="muted">Not added</span>';return esc(v||'Not added');}
export function requestsHTML(){const requests=state.requests.filter(r=>r.to===state.current||r.from===state.current);return requests.map(r=>'<div class="notice request"><div><strong>'+esc(member(r.from===state.current?r.to:r.from)?.name)+'</strong><p>'+(r.from===state.current?'You confirmed meeting in person. Waiting for their confirmation.':r.parentApproved?'Confirmed meeting you in person. Does this match the person beside you?':'Waiting for their parent’s approval.')+'</p></div>'+(r.to===state.current?b('Confirm connection','accept-pair','primary small','data-id="'+r.id+'" '+(!r.parentApproved?'disabled':''))+b('Decline','decline-pair','small','data-id="'+r.id+'"'):'')+'</div>').join('');}
