import {state,current,member,connected,family} from './store.js';
import {esc,avatar,personLink,icon,button as b} from './ui.js';
import {now} from './model.js';
const modal=document.querySelector('#modal');
let returnFocus;
export function showModal(title,body){returnFocus=document.activeElement;modal.innerHTML='<div class="modal-heading"><h2 id="modal-title">'+title+'</h2>'+b('×','close','close-button','aria-label="Close dialog"')+'</div><div class="modal-body"><div class="form-error" role="alert" hidden></div>'+body+'</div>';if(!modal.open)modal.showModal();const first=modal.querySelector('textarea,input:not([type=checkbox]),select');if(first)first.focus();}
export function closeModal(){modal.close();if(returnFocus?.isConnected)returnFocus.focus();}
export function formError(message){const el=modal.open?modal.querySelector('.form-error'):null;if(el){el.textContent=message;el.hidden=false;el.scrollIntoView({block:'nearest'});}else return false;return true;}
export function composeModal(type='text',wall=state.current){
 const other=wall!==state.current;
 const audience=other?'<input type="hidden" name="audience" value="connections"><p class="help">Shared connections</p>':'<label>Audience<select name="audience"><option value="connections">My connections</option>'+(family(wall,state.current)?'<option value="family">My household only</option>':'')+'</select></label>';
 const household=state.members.filter(p=>family(p.id,state.current)).map(p=>esc(p.name)).join(', ');
 showModal(other?'Write on '+esc(member(wall)?.name)+'’s wall':'Write a post','<form id="post-form" data-wall="'+wall+'"><div class="compose-who">'+avatar(state.current)+'<div><strong>'+esc(current().name)+'</strong>'+audience+'</div></div>'+(other?'<div class="notice">Visible to you, '+esc(member(wall)?.name)+', and people connected to both of you. Published directly on their wall.</div>':household?'<p class="help">Your household: '+household+'.</p>':'')+'<label>Post type<select name="type" id="post-type">'+[['text','Text'],['photo','Photo / video'],['poll','Poll'],...(!other?[['challenge','Challenge']]:[])].map(([id,label])=>'<option value="'+id+'" '+(id===type?'selected':'')+'>'+label+'</option>').join('')+'</select></label><label><span id="text-label">'+(type==='challenge'?'The task':'What would you like to share?')+'</span><textarea name="text" rows="4" required maxlength="5000"></textarea></label><div id="post-extras">'+postExtras(type)+'</div><label class="check-label"><input type="checkbox" required> This is human-made content.</label><div class="modal-footer"><button class="primary">'+(type==='challenge'?'Reserve Stars & open':'Publish post')+'</button></div></form>');
}
export function postExtras(type){if(type==='photo')return '<label>Choose a picture or video<input type="file" name="media" required accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm"></label><p class="help">Up to 1.5 MB in this local demo. Videos never autoplay.</p>';if(type==='poll')return '<label>Poll options (one per line)<textarea name="options" rows="3" required placeholder="Saturday morning&#10;Sunday afternoon"></textarea></label>';if(type==='challenge')return '<label>Challenge title<input name="title" required maxlength="100" placeholder="Give your challenge a name"></label><div class="form-grid"><label>Submission format<select name="format"><option value="text">Written submission</option><option value="image">Photograph & caption</option><option value="video">Video & caption</option></select></label><label>Deadline (SGT)<input type="date" name="deadline" required min="'+new Date(now()+86400000).toISOString().slice(0,10)+'" value="'+new Date(now()+7*86400000).toISOString().slice(0,10)+'"></label></div><label>Judging criteria<textarea name="criteria" required rows="2" placeholder="Explain how you will select the winner."></textarea></label><label>Star prize · '+current().stars+' available<input name="prize" type="number" required min="1" max="'+current().stars+'" step="1" value="50"></label><div class="notice">You are the sole judge. Entry is free; one winner receives the whole prize. Ties go to the earliest qualifying entry. Cancellation or no qualifying entries returns the prize. Rules lock after the first entry.</div>';return '';}
export function editModal(){const me=current();const fields=[['bio','About you'],['interests','Interests (optional)'],['city','City (optional)'],['email','Email'],['phone','Phone'],['whatsapp','WhatsApp']];
 showModal('Edit your details','<form id="profile-form"><p class="help">Share a few things you enjoy doing or talking about. Separate interests with commas. You choose who sees each field.</p>'+fields.map(([key,label])=>'<div class="privacy-field"><label>'+label+(key==='bio'?'<textarea name="'+key+'" rows="3" maxlength="1000">'+esc(me[key])+'</textarea>':'<input name="'+key+'" '+(key==='email'?'type="email"':'')+' maxlength="250" value="'+esc(Array.isArray(me[key])?me[key].join(', '):me[key])+'">')+'</label><label class="visibility-label">Who can see this?<select name="'+key+'Privacy">'+[['me','Only me'],['family','Family'],['connections','Connections']].map(([value,text])=>'<option value="'+value+'" '+(me.privacy[key]===value?'selected':'')+'>'+text+'</option>').join('')+'</select></label></div>').join('')+'<div class="modal-footer"><span class="help">Profiles are never public.</span><button class="primary">Save profile</button></div></form>');
}
export function connectModal(){
 const next=state.members.find(p=>p.id!==state.current&&!connected(p.id,state.current)&&!state.requests.some(r=>r.from===state.current&&r.to===p.id||r.to===state.current&&r.from===p.id));
 showModal('A connection starts with hello.','<div class="pair-illustration" aria-hidden="true">[ you ] &nbsp;⌁&nbsp; [ them ]</div><p>When you are together, bring your phones close. Both people confirm before a connection is added.</p><div class="notice"><strong>Local demo</strong><p>No Bluetooth, NFC, camera or location is accessed. The button below simulates another demo member’s phone.</p></div>'+(next?b('Simulate a nearby phone','nearby','primary full','data-id="'+next.id+'"'):'<p>You’re connected to everyone currently available. Create another member from the join demo to try pairing again.</p>'));
}
export function nearbyModal(id){showModal('Is this the person beside you?','<div class="pair-person">'+avatar(id,'large')+'<h2>'+esc(member(id)?.name)+'</h2><span class="badge">'+(member(id)?.parent?'Family account':'Identity verified · demo')+'</span></div><p>Confirm only after checking the person and their phone in front of you. They will need to confirm too.</p>'+b('Yes, we met in person','request-pair','primary full','data-id="'+id+'"')+'<p class="help">Then switch to '+esc(member(id)?.name)+' using the demo profile switcher to accept the request.</p>');}
