import {themeGallery} from './themes.js';
import {state,current,member,connected,family,visibleField,canSeePost,feedPosts} from './store.js';
import {esc,avatar,personLink,stamp,icon,heading,button as b,empty} from './ui.js';
import {composer,postList,caughtUp,fieldValue,renderPost,requestsHTML,mediaHTML} from './components.js';
import {allowed,canMessage,challengeVisible,deadlinePassed,now} from './model.js';
export const ui={query:'',city:'',profileTab:'wall',settingsTab:'account'};
export function feed(){
 const posts=feedPosts();
 return heading(new Date(now()).toLocaleDateString('en-SG',{weekday:'long',day:'numeric',month:'long'}).toUpperCase(),'Hi, '+esc(current().name.split(' ')[0])+'.','<span class="chronological">Newest first</span>')+composer()+postList(posts)+(posts.length?caughtUp():empty('No posts yet.','Posts from your connections will appear here.'));
}
export function connections(){
 const people=state.members.filter(m=>m.id!==state.current&&connected(m.id,state.current));
 const words=ui.query.trim().toLowerCase().split(/\s+/).filter(Boolean);
 const filtered=people.filter(p=>(!ui.city||visibleField(p.id,'city')&&p.city===ui.city)&&words.every(w=>[p.name,...(visibleField(p.id,'interests')?p.interests||[]:[])].join(' ').toLowerCase().includes(w)));
 const cities=[...new Set(people.filter(p=>visibleField(p.id,'city')).map(p=>p.city).filter(Boolean))];
 return '<section class="connections-page">'+heading('CONNECTIONS','Your people.',b('Connect in person','connect','primary small'))+requestsHTML()+'<form id="search-form" class="search-form"><label class="grow"><span>Search by name or interest</span><input name="query" value="'+esc(ui.query)+'" placeholder="Name or interest"></label><label><span>City</span><select name="city"><option value="">Any city</option>'+cities.map(c=>'<option '+(c===ui.city?'selected':'')+'>'+esc(c)+'</option>').join('')+'</select></label><button class="primary">Search</button></form><p class="help">Search only includes interests and cities shared with you.</p><div class="section-label">'+filtered.length+' '+(filtered.length===1?'PERSON':'PEOPLE')+' · ALPHABETICAL</div><div class="directory">'+filtered.sort((a,b)=>a.name.localeCompare(b.name)).map(p=>'<article class="directory-row"><a class="directory-avatar" href="#profile/'+p.id+'" aria-label="View '+esc(p.name)+'’s profile">'+avatar(p.id)+'</a>'+'<div class="grow"><h3>'+personLink(p.id)+'</h3>'+(visibleField(p.id,'city')&&p.city?'<p>'+esc(p.city)+'</p>':'')+'</div><div class="row-actions">'+'<a class="small directory-message" href="#messages/'+p.id+'" aria-label="Message '+esc(p.name)+'">Message</a></div></article>').join('')+'</div>'+(filtered.length?'':empty('No matches in your circle.','Try a different interest or city. Private fields are never included.'))+'</section>';
}
export function profile(id=state.current){
 const p=member(id);if(!p||!connected(id,state.current))return heading('PRIVATE PROFILE','A connection comes first.')+empty('Meet in person.','Profiles are available only to their existing connections.');
 const own=id===state.current;
 const fields=[['bio','About'],['city','City'],['interests','Interests'],['email','Email'],['phone','Phone'],['whatsapp','WhatsApp']];
 const pending=state.posts.filter(x=>x.wall===id&&x.pending&&canSeePost(x));
 const posts=state.posts.filter(x=>x.wall===id&&!x.pending&&canSeePost(x)).sort((a,b)=>b.created.localeCompare(a.created));
 return '<div class="profile-header">'+avatar(id,'large')+'<div class="grow"><div class="eyebrow">'+(own?'ME':'WALL')+'</div><h1>'+esc(p.name)+'</h1><p>'+esc(visibleField(id,'city')?p.city:'')+'</p><span class="badge">'+(p.parent?'Family account · age '+p.age:p.verified?'✓ Identity verified · demo':'Identity verification pending')+'</span></div>'+(own?b('Edit details','edit-profile','small'):'')+'</div><div class="profile-summary">'+fieldValue(p,'bio')+'</div>'+(own?'<div class="profile-wallet"><a href="#stars">☆ '+p.stars+' Stars · view balance & history →</a></div>':'')+'<div class="feed-filter profile-tabs"><div>'+[['wall','Wall'],['about','About & contact']].map(([v,label])=>b(label,'profile-tab',ui.profileTab===v?'selected':'','data-value="'+v+'"')).join('')+'</div>'+(own?'<a href="#settings">Privacy & settings →</a>':'<a href="#messages/'+id+'">Send a message →</a>')+'</div>'+
 (ui.profileTab==='about'?'<section class="detail-table">'+fields.map(([key,label])=>'<div><dt>'+label+'</dt><dd>'+fieldValue(p,key)+(own?'<span class="field-audience">'+(p.privacy[key]==='me'?'Only me':p.privacy[key]==='family'?'Family':'Connections')+'</span>':'')+'</dd></div>').join('')+'</section>':
 (pending.length?'<div class="section-label">'+(own?'PREVIOUSLY HELD POSTS':'YOUR PREVIOUSLY HELD POSTS')+' · '+pending.length+'</div>'+pending.map(renderPost).join(''):'')+composer(id)+postList(posts)+(posts.length?'':empty('A wall, ready for life.','Share a thought, a photograph, or something you’ve been making.')));
}
export function messages(to){
 const peers=state.members.filter(p=>p.id!==state.current&&connected(p.id,state.current));
 if(!to)to=peers.find(p=>state.messages.some(m=>m.from===p.id&&m.to===state.current||m.to===p.id&&m.from===state.current))?.id||peers[0]?.id;
 const selected=member(to);const valid=selected&&connected(to,state.current)&&to!==state.current;
 const chat=valid?state.messages.filter(m=>m.from===state.current&&m.to===to||m.from===to&&m.to===state.current).sort((a,b)=>a.created.localeCompare(b.created)):[];
 return '<div class="page-heading"><h1>Messages</h1></div>'+'<div class="messenger"><aside class="conversation-list">'+peers.map(p=>{const list=state.messages.filter(m=>m.from===p.id&&m.to===state.current||m.to===p.id&&m.from===state.current);const last=list.at(-1);return '<a href="#messages/'+p.id+'" class="conversation '+(p.id===to?'selected':'')+'">'+avatar(p.id,'tiny')+'<div><strong>'+esc(p.name)+'</strong><p>'+esc(last?.text||'Say hello')+'</p></div></a>';}).join('')+'</aside><section class="chat">'+(valid?'<div class="chat-header">'+avatar(to,'tiny')+'<div><strong>'+esc(selected.name)+'</strong><span>Private · '+(canMessage(state.current,to)?'Connected in person':'Messaging restricted by a parent')+'</span></div></div><div class="chat-history">'+(chat.length?chat.map(m=>'<div class="message '+(m.from===state.current?'mine':'')+'"><div>'+esc(m.text)+mediaHTML(m.media,m.mediaType,'Message attachment')+'</div><time>'+stamp(m.created)+'</time></div>').join(''):empty('The beginning of a conversation.','Send a note to '+esc(selected.name.split(' ')[0])+'.'))+'</div>'+(canMessage(state.current,to)?'<form id="message-form" data-to="'+to+'" class="message-form"><label class="sr-only" for="message-text">Your message</label><textarea id="message-text" name="text" placeholder="Write a message…" rows="2" maxlength="5000"></textarea><div class="message-controls"><label class="attachment">▧ <span>Photo / video</span><input type="file" name="media" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm"></label><button class="primary small">Send message</button></div><p class="help">Attachments up to 1.5 MB in this local demo.</p></form>':'<div class="notice">A parent has disabled messaging for this account.</div>'):empty('No conversation selected.','Connect with someone in person to start messaging.'))+'</section></div>';
}
export function challenge(id){
 const c=state.challenges.find(c=>c.id===id);if(!c||!challengeVisible(c))return empty('This challenge is private.','You need to be in the wall owner’s audience to view it.');
 const entries=c.entries.filter(e=>connected(e.author,state.current));
 const judge=c.judge===state.current,entered=c.entries.some(e=>e.author===state.current),closed=deadlinePassed(c);
 const format=c.format==='text'?'Written submission':c.format==='video'?'Video and caption':'One photograph and a caption';
 return '<a class="back-link" href="#feed">← Back to feed</a>'+heading('A CHALLENGE BETWEEN FRIENDS',esc(c.title))+'<div class="challenge-banner"><div><span class="eyebrow">'+(c.status==='awarded'?'PRIZE AWARDED':c.status==='cancelled'?'PRIZE RETURNED':'RESERVED PRIZE')+'</span><strong>☆ '+c.prize+' <small>Stars</small></strong></div><span class="badge">'+(c.status==='awarded'?'Awarded':c.status==='cancelled'?'Cancelled':closed?'Ready for judging':'Open for entries')+'</span></div><section class="paper-section"><h2>The task</h2><p>'+esc(c.task)+'</p><dl class="challenge-details"><div><dt>Submit</dt><dd>'+format+'</dd></div><div><dt>Deadline</dt><dd>'+esc(c.deadline)+' · 11:59 pm SGT</dd></div><div><dt>Judging criteria</dt><dd>'+esc(c.criteria)+'</dd></div><div><dt>One judge</dt><dd>'+personLink(c.judge)+'</dd></div><div><dt>Entry</dt><dd>Free · one entry per person · one winner</dd></div></dl><details><summary>Full rules & what happens to the prize</summary><p>'+esc(c.rules)+'</p><p>Stars have no cash withdrawal value. '+(c.reserved?c.reserved+' Stars are reserved and cannot be spent elsewhere.':'The reserved prize has been settled.')+'</p></details></section>'+
 (c.status==='awarded'?'<div class="winner-banner">☆ Awarded to '+(connected(c.winner,state.current)?personLink(c.winner):'a member outside your connections')+' · '+c.prize+' Stars transferred</div>':c.status==='cancelled'?'<div class="notice"><strong>Prize returned to the creator.</strong><p>'+esc(c.reason)+'</p></div>':
 judge?'<div class="notice"><strong>You are the judge.</strong><p>'+(closed?'Choose one winner below or return the prize if no entry qualifies.':'Entries stay open until the deadline. The rules cannot be changed once someone enters.')+'</p>'+(!closed?b('Demo: move past deadline','advance-clock','small','data-id="'+c.id+'"'):'')+' '+b('Cancel / no qualifying entries','cancel-challenge','small','data-id="'+c.id+'"')+'</div>':
 entered?'<div class="notice">✓ Your entry is submitted. The judge will decide after the deadline.</div>':
 closed?'<div class="notice">Submissions are closed. Waiting for '+esc(member(c.judge)?.name)+' to judge.</div>':
 '<section class="paper-section"><h2>Your entry</h2><form id="entry-form" data-id="'+c.id+'"><label>Submission / caption<textarea name="text" required rows="4" maxlength="5000" placeholder="Tell us what you made or noticed."></textarea></label>'+(c.format!=='text'?'<label>'+format+'<input type="file" name="media" required accept="'+(c.format==='video'?'video/mp4,video/webm':'image/jpeg,image/png,image/webp,image/gif')+'"></label><p class="help">Up to 1.5 MB in this local demo.</p>':'')+'<label class="check-label"><input type="checkbox" required> This is my own work, made without generative AI. I agree to the published rules.</label><button class="primary">Submit entry · free</button><p class="help">Visible to the judge and your connections who can see this challenge.</p></form></section>')+
 '<div class="section-label">SUBMISSIONS · '+entries.length+'</div>'+entries.map(e=>'<article class="paper-section entry">'+personLink(e.author)+'<span class="metadata"> · '+stamp(e.created)+'</span><p>'+esc(e.text)+'</p>'+mediaHTML(e.media,e.mediaType,e.text)+(judge&&closed&&c.status==='open'?b('Award '+c.prize+' Stars to '+esc(member(e.author)?.name.split(' ')[0]),'award','primary small','data-id="'+c.id+'" data-entry="'+e.id+'"'):'')+b('Report entry','report-entry','link-button small','data-id="'+e.id+'"')+'</article>').join('')+(!entries.length?empty('No entries to show.','Submissions from people you know appear here.'): '');
}
export function stars(){
 const me=current();const reserved=state.challenges.filter(c=>c.creator===me.id).reduce((sum,c)=>sum+c.reserved,0);
 return heading('KEEP. GIVE. MAKE SOMETHING HAPPEN.','Your Stars.')+'<div class="wallet"><div><span class="eyebrow">AVAILABLE TO GIVE</span><strong>☆ '+me.stars+'</strong></div><div><span class="eyebrow">RESERVED IN CHALLENGES</span><strong>'+reserved+'</strong></div></div><p class="help">Received Stars are yours to keep, gift, or put toward a challenge. No cash withdrawals.</p><div class="paper-section"><h2>A little extra appreciation.</h2><p>Membership includes 100 Stars each month. Additional Stars are optional.</p><p><strong>Proposed demo price: S$0.01 per Star.</strong><br>Currency, price and allowance are assumptions to test.</p>'+(!me.parent?b('Add Stars','buy-stars','primary'):'<p class="notice">Only an adult can purchase Stars. Your parent can gift them to you.</p>')+'</div><div class="section-label">BALANCE & PURCHASE HISTORY</div><div class="ledger">'+state.ledger.filter(l=>l.member===me.id).sort((a,b)=>b.created.localeCompare(a.created)).map(l=>'<div><span>'+esc(l.label)+'<time>'+stamp(l.created)+'</time></span><strong class="'+(l.amount>0?'positive':'')+'">'+(l.amount>0?'+':'')+l.amount+' ☆</strong></div>').join('')+'</div>';
}
export function settings(){
 const me=current(),children=state.members.filter(m=>m.parent===me.id);
 return heading('YOUR ACCOUNT, YOUR CHOICE','Membership & settings.')+themeGallery()+'<section class="paper-section"><div class="section-top"><h2>'+ (me.plan==='family'?'Family':'Individual')+' membership</h2><span class="badge">'+esc(me.membership)+'</span></div><p>'+ (me.plan==='family'?'S$6':'S$3')+' per month · proposed demo pricing<br>100 Stars per member, per month.</p><p class="help">No real subscription or payment exists in this demo.</p>'+(!me.parent?b(me.membership==='active'?'Cancel membership':'Resume membership',me.membership==='active'?'cancel-membership':'resume-membership','small'):'<p>Managed by '+personLink(me.parent)+'.</p>')+'</section><section class="paper-section"><div class="section-top"><h2>Your Stars</h2><span class="badge">☆ '+me.stars+' available</span></div><p><a href="#stars">View balance, gifts & purchase history →</a></p></section><section class="paper-section"><h2>Profile & privacy</h2><p>Your profile is private. Choose the audience for each field. Only manually selected cities are used.</p>'+b('Edit profile & field visibility','edit-profile','small')+'</section>'+
 (children.length?'<section class="paper-section"><h2>Your family</h2><p>Children are covered by your family membership.</p>'+children.map(c=>'<form class="family-form" data-id="'+c.id+'"><div class="section-top"><strong>'+esc(c.name)+' · '+c.age+'</strong>'+avatar(c.id,'tiny')+'</div>'+[['posting','Can post and enter challenges'],['messages','Can message permitted connections'],['stars','Can give Stars and fund challenges'],['connections','Can accept new in-person connections']].map(([key,label])=>'<label class="check-label"><input type="checkbox" name="'+key+'" '+(c.controls[key]?'checked':'')+'> '+label+'</label>').join('')+'<button class="small">Save parental controls</button></form>').join('')+
 state.requests.filter(r=>children.some(c=>c.id===r.from)&&!r.parentApproved).map(r=>'<div class="notice">'+esc(member(r.from)?.name)+' met '+esc(member(r.to)?.name)+'. '+b('Approve connection request','parent-pair','small','data-id="'+r.id+'"')+'</div>').join('')+'</section>':'')+
 '<section class="paper-section"><h2>Human review & appeals</h2><p><a href="#about">Read the Same Old Faces agreement →</a></p><p>Report AI-generated content, harassment, or privacy concerns from any post. Reviews and appeals are handled by people.</p><p class="help">This prototype records reports locally. No report is sent to a moderation team.</p>'+state.reports.filter(r=>r.reporter===me.id).map(r=>'<div class="report-row"><strong>'+esc(r.reason)+'</strong><p>'+esc(r.status)+(r.appeal?' · Appeal: '+esc(r.appeal):'')+'</p>'+b('Appeal / add context','appeal','small','data-id="'+r.id+'"')+'</div>').join('')+'</section><section class="paper-section"><h2>Your data belongs to you.</h2><p>Export your account data as JSON. Deleting a demo account removes its profile, posts and messages from this browser.</p><div class="button-row">'+b('Export my data','export','small')+b('Delete demo account','delete-account','danger small')+'</div></section><section class="paper-section demo-settings"><h2>Demo controls</h2><p>All identities, verification, payments, connections and moderation are simulated. Content and settings are saved only in this browser.</p><div class="button-row"><a href="#welcome">Preview join & membership →</a>'+b('Reset all demo data','reset','small')+'</div></section>';
}
export function about(){return '<div class="landing-heading"><div class="eyebrow">A PRIVATE NETWORK FOR REAL LIFE</div><h1>A smaller internet.<br>A fuller life.</h1><p>Your people. Their everyday lives. A place to stay close, without an audience of strangers.</p><a href="#welcome" class="button primary">Become a member</a><a href="#feed">Enter the demo →</a></div><div class="aggregate-stats">'+[[state.members.length,'Members'],[state.members.length,'Active in 30 days'],[state.posts.filter(p=>p.type==='photo'&&!p.pending).length,'Pictures posted'],[state.challenges.length,'Challenges created']].map(([n,label])=>'<div><strong>'+n+'</strong><span>'+label+'</span></div>').join('')+'</div><p class="help">Aggregate counts from the family demo. Member profiles and posts remain private.</p><section class="paper-section"><h2>People before the platform.</h2><p>Same Old Faces is a paid, private social network for people and families. Connect face to face, share on your wall, and find the things you have in common.</p><div class="principles"><div><span>01</span><h3>Your time is yours.</h3><p>A chronological feed with an end. No autoplay, streaks, engagement ranking, or advertising.</p></div><div><span>02</span><h3>Private from the start.</h3><p>No public people search or stranger recommendations. You decide who sees each detail.</p></div><div><span>03</span><h3>Made by humans.</h3><p>No AI agents or AI-generated posts, media, messages, or entries. People review reports and appeals. We cannot detect every instance of AI use.</p></div><div><span>04</span><h3>Good work gets a little thanks.</h3><p>Likes are free. Give Stars or set a challenge with a reserved prize, clear rules, and one winner. Entry is always free.</p></div></div></section><section class="paper-section"><h2>A membership that serves you.</h2><p>Proposed pricing: S$3 per month for an individual, S$6 for a family. Each member receives 100 Stars monthly. Optional Stars cost S$0.01 each. Pricing and currency are still being tested.</p><p>No cash withdrawals. No advertising. Cancellation, data export, and account deletion are easy to find.</p></section><p class="credits">Demo photograph: <a href="https://commons.wikimedia.org/wiki/File:20190819_Singapore_Botanic_Gardens_walkway-1.jpg" target="_blank" rel="noreferrer">Singapore Botanic Gardens</a> by Balon Greyjoy, CC0. Dog photos: <a href="https://commons.wikimedia.org/wiki/File:Image_of_golden_retriever.jpg" target="_blank" rel="noreferrer">Golden retriever</a> by A throne man, CC0; <a href="https://commons.wikimedia.org/wiki/File:Pembroke_Welsh_Corgi_Puppy.jpg" target="_blank" rel="noreferrer">corgi puppy</a> by Daniel Stockman, <a href="https://creativecommons.org/licenses/by-sa/2.0/" target="_blank" rel="noreferrer">CC BY-SA 2.0</a>, resized. Profiles use the supplied family personas. All posts, messages, challenge entries and activity are invented demo content. Dog photographs are illustrative, not family photographs.</p>';}
export function welcome(){return heading('A MEMBERSHIP, NOT AN AUDIENCE','Make yourself at home.')+'<section class="paper-section"><p>Try the complete joining experience with a fictional member. No real personal details or payment required.</p><form id="join-form"><label>Demo name<input name="name" required maxlength="50" placeholder="e.g. Robin Lee"></label><label>City (optional)<input name="city" maxlength="60" placeholder="Choose a city, not a precise location"></label><label>Membership<select name="plan"><option value="individual">Individual · S$3 / month</option><option value="family">Family · S$6 / month</option></select></label><label class="check-label"><input type="checkbox" required> Simulate adult identity verification.</label><label class="check-label"><input type="checkbox" required> I agree to the community rules: people only, no generated content, and respect for privacy.</label><div class="notice">Demo checkout · No charge. Prices are proposed. Includes 100 Stars each month. New profiles and contact fields are private by default.</div><button class="primary">Simulate payment & join</button></form></section>';}
